id: pipeline_DB_TO_DB_mergeINTO
namespace: pipeline-db-to-db-mergeinto
description: Import DB_to_DB data into MS SQL Server

tasks:
  
- id: select_all_encounter_procedure_tempdev_merge_into
  type: io.kestra.plugin.jdbc.sqlserver.Query
  sql: select * from [StgPanda].[ventiemr].[encounter_procedure_tempdev_merge_into]
  fetch: true
  
- id: Merge-into-update
  type: io.kestra.plugin.jdbc.sqlserver.Query
  sql:  "MERGE INTO [StgPanda].[ventiemr].[encounter_procedure_tempdev_merge_intotest] AS TARGET
      USING [StgPanda].[ventiemr].[encounter_procedure_tempdev_merge] AS SOURCE 
      ON (TARGET.updated_at = SOURCE.updated_at) 
      WHEN MATCHED AND 
               TARGET.encounter_id <> SOURCE.encounter_id 
               OR TARGET.note <> SOURCE.note
               OR TARGET.department_name <> SOURCE.department_name
               OR TARGET.hospital_name <> SOURCE.hospital_name
               OR TARGET.zone_id <> SOURCE.zone_id
               OR TARGET.disposition_type_name <> SOURCE.disposition_type_name
               OR TARGET.disposition_type_display <> SOURCE.disposition_type_display
               OR TARGET.disposition_type_display_th <> SOURCE.disposition_type_display_th
      		 OR TARGET.updated_at <> SOURCE.updated_at
      
      THEN 
          UPDATE 
          SET TARGET.encounter_id = SOURCE.encounter_id,
              TARGET.note = SOURCE.note,
              TARGET.department_name = SOURCE.department_name,
              TARGET.hospital_name = SOURCE.hospital_name,
              TARGET.zone_id = SOURCE.zone_id,
              TARGET.disposition_type_name = SOURCE.disposition_type_name,
              TARGET.disposition_type_display = SOURCE.disposition_type_display,
              TARGET.disposition_type_display_th = SOURCE.disposition_type_display_th,
      		TARGET.updated_at = SOURCE.updated_at
      WHEN NOT MATCHED BY TARGET 
      THEN 
          INSERT (
              encounter_id, note, department_name, hospital_name, 
              zone_id, disposition_type_name, disposition_type_display, 
              disposition_type_display_th,updated_at
          )          
          VALUES (
              SOURCE.encounter_id, SOURCE.note, SOURCE.department_name, 
              SOURCE.hospital_name,  SOURCE.zone_id, SOURCE.disposition_type_name, 
              SOURCE.disposition_type_display, SOURCE.disposition_type_display_th, SOURCE.updated_at
          )
      WHEN NOT MATCHED BY SOURCE 
      THEN 
          DELETE;"

- id: commit_and_push
  type: io.kestra.plugin.git.Push
  url: https://github.com/sunshinemanoson/krestra_pipeline
  branch: main
  username: sunshinemanoson
  password: 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
  namespaceFiles:
    enabled: true
  flows:
    enabled: true
  commitMessage: "add flows and scripts"
  
  

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"



taskDefaults:
  - type: io.kestra.plugin.jdbc.sqlserver.Query
    values:
      url: jdbc:sqlserver://sia09-icdvx1.sihmis.si:1433;databaseName=StgPanda;encrypt=true;trustServerCertificate=true
      username: 'UserDevPandaITF'
      password: 'P@ssword@ssis'



